### ISSUE TITLE
Columns development.

### ISSUE THREAD

**Issue by ugurcanlacin** [ugurcanlacin/SportClubSystem#32]
@KurtTaylan 
You can write columns are needed improving.So, We can discuss and decide changes.

**Comment by KurtTaylan** [comment]
User table , surname columns should not be default null :) Until so far , this is only mistake I guess.

**Comment by ugurcanlacin** [comment]
@KurtTaylan I am aware of this. But you are right. Users have to have their surnames.

**Comment by KurtTaylan** [comment]
ac255ded25ebe41afd9de78b00a96d9d53378cd4
