### ISSUE TITLE
Workout table development.

### ISSUE THREAD

**Issue by ugurcanlacin** [ugurcanlacin/SportClubSystem#33]
@KurtTaylan 
Workout is not enough to store data. So, We need to improve that table. As you said, There should be another table.We might name it as "exercise".So workout table would be used as program list. At the exercise table we define each step.I thought the table structure.Let me know your idea and suggestions.

muscle_region
id-int
name-varchar(6 region name will be stored here.)

-Exercise
id-int
exercise-varchar (like bench press etc.)
// will add one to many relationship with muscle region between exercise's id and muscle_region's id. For instance, One exercise may work for multiple regions.

-Workout(Alter)
will delete workoutprogram column
will add one to many relationship with exercise table between workout's id and exerise's id.
For instance, One workout program may have multiple exercise.

End of the story, when we want to prepare workout program, We can sort exercises according to muscle regions.And we will add that exercises to workout table.

**Comment by KurtTaylan** [comment]
First of all , we need two things to get all of this done;
1.As a result, we need Workout program made by Personal Trainer . This program should be taken from table called "workout". 
1.1.This table may have only one column for the record of workout program and we might do word search inside of this ONE COLUMN stuff.
1.2. And according to result we can fetch data from our table "exercise" for the significant exercise video which are written on the workout plan.
1. Exercise table for specified class-path of the media on our server depends on workout exercise.
   2.1. This table consist of 6 different columns according to muscle part of body and it might be more according to what we need from table to do.

Approach this subject first ideological not implement based. But, your idea for designing of the database part seems to need little touch to be perfect . 

Edit: Little idea;

its two tables;

Table:      workout_plan
columns: id_workout-int(11), program - varchar(2000)

Table:      exercise_library
columns: id_exercise-int(11) , chest - varchar(100), back- varchar(100), arms- varchar(100), legs- varchar(100), shoulders- varchar(100), timestamp. date. it can be more here...

this two tables have got one to many relationship.

**Comment by ugurcanlacin** [comment]
![plan](https://cloud.githubusercontent.com/assets/6627185/9028394/da3ea9de-397f-11e5-928b-52fff91fe91d.png)
