### ISSUE TITLE
Needed design for user proccess

### ISSUE THREAD

**Issue by ugurcanlacin** [ugurcanlacin/SportClubSystem#35]

**Comment by KurtTaylan** [comment]
http://kolayspor.com/ceo/ 

We can get some idea about what we can involved into project from here. Also , when I saw admin panel I couldn't understand what is the difference between , user management and customer management ?

edit: One more thing, I guess we should fill context of project in by Turkish language first than we should add internalization for English language.
Edit 2: https://www.facebook.com/maksigym/timeline   here is facebook page of the company that its so similar to our idea. @ugurcanlacin

**Comment by ugurcanlacin** [comment]
@KurtTaylan
The link doesn't work.
The difference between user management  and customer management is user management  is related adding account for system and its management like role,access details(username,password etc.) On the other hand, Customer management is related that account's informations like what account has workout plan or diet program. 

For edit 1: I think you are right. We should do this.
For edit 2:  I looked at that page. Do they have mobile application like we thought?

**Comment by KurtTaylan** [comment]
@ugurcanlacin  when you click the link you will face with login page and credentials are;
username:demo,
password:demo.

they have only trace system and they have got responsive . When you enter from mobile you see suitable interface.

**Comment by KurtTaylan** [comment]
@ugurcanlacin  I have a few things about General system rather than just User management. These photos are some of them ;

![admin panel first page](https://cloud.githubusercontent.com/assets/9060924/9081202/21a656fc-3b63-11e5-9ecb-e253cb18741f.png)

This is the first page for admin entrance. 

![admin panel- management section first page](https://cloud.githubusercontent.com/assets/9060924/9081223/42608aac-3b63-11e5-9a78-36aa5031d364.png)

This is the first page for Admin/Management first page.

**Comment by KurtTaylan** [comment]
@ugurcanlacin  I have gone through this process and I have good solution to this issue;

Our admin Main page is;

![admin panel - main page - new page](https://cloud.githubusercontent.com/assets/9060924/9106906/3759ef8a-3c2c-11e5-83b1-52b0133bc730.png)

Edit2: @ugurcanlacin  I forgot to tell you what "Salon takip" means for the application. It means when Admin click on it he/she can see instant status of the Gym in that moment. He/she can see who are inside who are not, if there is some problem about customers in that moment etc.

And you said we should focus on Management part so I did;

![admin-management page - new page](https://cloud.githubusercontent.com/assets/9060924/9106932/5de667d2-3c2c-11e5-9b12-8c79ec74bd5f.png)

As you can see we have 4 sub sections;

I have sent you about 4 sub sections's scenarios from Evernote. But I created common sub page view.
Here it is;

![admin panel - common sub page](https://cloud.githubusercontent.com/assets/9060924/9107066/42c47d3a-3c2d-11e5-8aa4-2e99b1efc980.png)

![admin panel - common sub click menu page](https://cloud.githubusercontent.com/assets/9060924/9107073/487f178a-3c2d-11e5-9d9e-884face5dd56.png)

Edit: I know you wanted % 100 detailed planning but first I had to specify general line before I make a detailed planning. After this I am going to design inside of sub pages.

**Comment by ugurcanlacin** [comment]
http://miwisoft.com/joomla-extensions/mijoevents-manage-book-events

**Comment by KurtTaylan** [comment]
@ugurcanlacin  How about now?

![last version of dashboard](https://cloud.githubusercontent.com/assets/9060924/9111465/058b0b78-3c50-11e5-8618-18a982685aa2.png)

plus;

![user management](https://cloud.githubusercontent.com/assets/9060924/9111712/40224e84-3c52-11e5-996b-f0c2547b058a.png)

plus2;

![customer management](https://cloud.githubusercontent.com/assets/9060924/9111779/ea74e234-3c52-11e5-9acd-15ffe8cfb3bc.png)

plus3;

![customer management 2](https://cloud.githubusercontent.com/assets/9060924/9111845/53d92190-3c53-11e5-8fbe-40ae868cf382.png)
