### ISSUE TITLE
Template Decision

### ISSUE THREAD

**Issue by ugurcanlacin** [ugurcanlacin/SportClubSystem#36]

**Comment by ugurcanlacin** [comment]
@KurtTaylan 
Generally, We have two choices.Material design and Bootstrap. I prefer Bootstrap cause it is more pure. You can look at the links on the below to get idea what bootstrap and material design look like.

One of Bootstrap templates.
http://themeforest.net/item/quirk-bootstrap-admin-template/12189223

One of Material design templates.
http://themeforest.net/item/altair-material-design-premium-template/12190654

Thus,We can eliminate big part and focus one of them to find best choice for us.

**Comment by ugurcanlacin** [comment]
http://themeforest.net/item/oneui-admin-dashboard-template-ui-framework/11820082
http://themeforest.net/item/matmix-components-mix-bootstrap-admin-dashboard/12099504
http://themeforest.net/item/ultra-admin/10865235
http://themeforest.net/item/atlant-bootstrap-admin-template-with-frontend/9217590

**Comment by KurtTaylan** [comment]
@ugurcanlacin I guess we can choose between Atlant and OneUI..

What are you thinking?

**Comment by ugurcanlacin** [comment]
@KurtTaylan 
http://themeforest.net/item/slicklab-responsive-admin-dashboard-template/10805428
http://themeforest.net/item/appui-web-app-bootstrap-admin-template/8603616
http://themeforest.net/item/xenon-bootstrap-admin-theme-with-angularjs/9059661 (It has member list,add member at Extra->Members section.)
http://themeforest.net/item/mtek-admin-template-bootstrap-angularjs/9582169 (Profile page is awesome.But I dont like colors.)

**Comment by ugurcanlacin** [comment]
@KurtTaylan 
http://themeforest.net/item/sentir-responsive-admin-and-dashboard-ui-kits/7700260

**Comment by KurtTaylan** [comment]
@ugurcanlacin My choices are Atlant and Mtek what you think ?

**Comment by ugurcanlacin** [comment]
@KurtTaylan  I'm confused :/

**Comment by KurtTaylan** [comment]
@ugurcanlacin Our priority is theme back-end focused. We should look after them firstly.

**Comment by ugurcanlacin** [comment]
@KurtTaylan 
http://themeforest.net/item/adminre-responsive-frontend-and-backend-theme/7133307
Tab system is included.Forms are great.Datatables also is awesome I think.

**Comment by KurtTaylan** [comment]
@ugurcanlacin it seems nice about things you have mentioned above . Only thing is it seems little childish or ? Maybe , Wè can use it as a modern way ?

**Comment by ugurcanlacin** [comment]
We have chosen Atlant template.
